### ISSUE TITLE
top dir

### ISSUE THREAD

**Issue by tgkprog** [thaliproject/android-peer-discovery#2]
looks like you forget to commit the top level directory where the module is defined

**Comment by yaronyg** [comment]
This repo is abandoned. The pure Android P2P discovery code now lives in https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary which also has a sample app. But our primary usage of that repo is in our Node based Cordova plugin, you can see that Java code at https://github.com/thaliproject/Thali_CordovaPlugin/tree/master/src/android/java/io/jxcore/node.
